<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Barbearia.Domain\Barbearia.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Servicos\" />
    <Folder Include="Validacoes\" />
    <Folder Include="Interfaces\" />
    <Folder Include="DTOs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.11" />
  </ItemGroup>

</Project>
